import type { DashboardState } from "./types";

export const DEMO_OWNER_ID = "demo@signalcast.local";

export const demoState: DashboardState = {
  interests: [
    {
      id: "interest-ai-agents",
      name: "AI agents",
      query: "autonomous AI agents, tool use, planning, and agent evaluation",
      keywords: ["agents", "tool use", "planning"],
      exclusions: ["marketing"],
      preferredSources: ["arXiv", "Semantic Scholar"],
      freshnessDays: 30,
      weight: 1,
      enabled: true,
    },
    {
      id: "interest-efficient-models",
      name: "Efficient models",
      query: "efficient language models, quantization, inference, and state space models",
      keywords: ["quantization", "inference", "state space"],
      exclusions: [],
      preferredSources: ["OpenAlex", "arXiv"],
      freshnessDays: 45,
      weight: 0.9,
      enabled: true,
    },
    {
      id: "interest-robotics",
      name: "Embodied intelligence",
      query: "robotics, vision-language-action models, and embodied intelligence",
      keywords: ["robotics", "VLA", "embodied"],
      exclusions: [],
      preferredSources: ["Semantic Scholar"],
      freshnessDays: 30,
      weight: 0.8,
      enabled: true,
    },
  ],
  sources: [
    {
      id: "source-openalex",
      name: "OpenAlex",
      type: "openalex",
      url: "https://api.openalex.org",
      trustLevel: "primary",
      rightsMode: "metadata_only",
      enabled: true,
      lastSuccessfulFetch: "2026-07-25T05:31:00+05:30",
    },
    {
      id: "source-semantic",
      name: "Semantic Scholar",
      type: "semantic_scholar",
      url: "https://api.semanticscholar.org",
      trustLevel: "primary",
      rightsMode: "metadata_only",
      enabled: true,
      lastSuccessfulFetch: "2026-07-25T05:31:12+05:30",
    },
    {
      id: "source-arxiv",
      name: "arXiv",
      type: "arxiv",
      url: "https://export.arxiv.org/api/query",
      trustLevel: "primary",
      rightsMode: "open_access",
      enabled: true,
      lastSuccessfulFetch: "2026-07-25T05:31:22+05:30",
    },
    {
      id: "source-cloudflare",
      name: "Cloudflare Blog",
      type: "rss",
      url: "https://blog.cloudflare.com/rss/",
      trustLevel: "trusted",
      rightsMode: "feed_only",
      enabled: true,
      lastSuccessfulFetch: "2026-07-25T05:32:00+05:30",
    },
    {
      id: "source-huggingface",
      name: "Hugging Face Blog",
      type: "rss",
      url: "https://huggingface.co/blog/feed.xml",
      trustLevel: "trusted",
      rightsMode: "feed_only",
      enabled: true,
      lastSuccessfulFetch: "2026-07-25T05:32:04+05:30",
    },
  ],
  items: [
    {
      id: "paper-deepseek-r1",
      kind: "paper",
      title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
      summary:
        "A family of reasoning models trained with large-scale reinforcement learning, including analysis of emergent reasoning behaviors and distillation into smaller models.",
      authors: ["DeepSeek-AI"],
      sourceName: "arXiv",
      sourceId: "source-arxiv",
      canonicalUrl: "https://arxiv.org/abs/2501.12948",
      arxivId: "2501.12948",
      publishedAt: "2025-01-22T00:00:00Z",
      accessLevel: "open_access",
      peerReviewState: "preprint",
      topics: ["Reasoning", "Reinforcement learning", "Language models"],
      score: 96,
      trend: "rising",
      citationCount: 1246,
      readingMinutes: 42,
      saved: true,
      listened: false,
      processingState: "ready",
    },
    {
      id: "paper-mamba",
      kind: "paper",
      title: "Mamba: Linear-Time Sequence Modeling with Selective State Spaces",
      summary:
        "Selective state space models offer a recurrent alternative to attention with linear scaling in sequence length and strong performance across several modalities.",
      authors: ["Albert Gu", "Tri Dao"],
      sourceName: "arXiv",
      sourceId: "source-arxiv",
      canonicalUrl: "https://arxiv.org/abs/2312.00752",
      arxivId: "2312.00752",
      publishedAt: "2023-12-01T00:00:00Z",
      accessLevel: "open_access",
      peerReviewState: "preprint",
      topics: ["State space models", "Efficient inference"],
      score: 92,
      trend: "foundational",
      citationCount: 2831,
      readingMinutes: 31,
      saved: false,
      listened: true,
      processingState: "ready",
    },
    {
      id: "paper-flashattention",
      kind: "paper",
      title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
      summary:
        "An exact attention algorithm that reduces memory traffic between high-bandwidth memory and on-chip SRAM through tiling.",
      authors: ["Tri Dao", "Daniel Fu", "Stefano Ermon"],
      sourceName: "NeurIPS",
      canonicalUrl: "https://arxiv.org/abs/2205.14135",
      arxivId: "2205.14135",
      publishedAt: "2022-05-27T00:00:00Z",
      accessLevel: "open_access",
      peerReviewState: "peer_reviewed",
      topics: ["Attention", "GPU systems", "Efficient inference"],
      score: 91,
      trend: "foundational",
      citationCount: 5690,
      readingMinutes: 29,
      saved: true,
      listened: true,
      processingState: "ready",
    },
    {
      id: "paper-bitnet",
      kind: "paper",
      title: "The Era of 1-bit LLMs: All Large Language Models are in 1.58 Bits",
      summary:
        "BitNet b1.58 explores ternary parameters as a path toward lower memory, latency, and energy requirements for language-model inference.",
      authors: ["Shuming Ma", "Hongyu Wang", "Lingxiao Ma"],
      sourceName: "arXiv",
      sourceId: "source-arxiv",
      canonicalUrl: "https://arxiv.org/abs/2402.17764",
      arxivId: "2402.17764",
      publishedAt: "2024-02-27T00:00:00Z",
      accessLevel: "open_access",
      peerReviewState: "preprint",
      topics: ["Quantization", "Efficient models"],
      score: 89,
      trend: "rising",
      citationCount: 988,
      readingMinutes: 18,
      saved: false,
      listened: false,
      processingState: "ready",
    },
    {
      id: "paper-attention",
      kind: "paper",
      title: "Attention Is All You Need",
      summary:
        "The Transformer replaces recurrence and convolution with attention, enabling greater parallelism and establishing a new foundation for sequence modeling.",
      authors: ["Ashish Vaswani", "Noam Shazeer", "Niki Parmar"],
      sourceName: "NeurIPS",
      canonicalUrl: "https://arxiv.org/abs/1706.03762",
      arxivId: "1706.03762",
      publishedAt: "2017-06-12T00:00:00Z",
      accessLevel: "open_access",
      peerReviewState: "peer_reviewed",
      topics: ["Transformers", "Attention"],
      score: 99,
      trend: "foundational",
      citationCount: 146000,
      readingMinutes: 24,
      saved: true,
      listened: true,
      processingState: "ready",
    },
    {
      id: "blog-edge-ai",
      kind: "blog",
      title: "Why smaller models are moving inference back to the edge",
      summary:
        "A practical look at how quantization, better runtimes, and specialized hardware are changing the economics of private on-device AI.",
      authors: ["SignalCast editorial"],
      sourceName: "Hugging Face Blog",
      sourceId: "source-huggingface",
      canonicalUrl: "https://huggingface.co/blog",
      publishedAt: "2026-07-24T08:30:00Z",
      accessLevel: "feed_content",
      peerReviewState: "unknown",
      topics: ["Edge AI", "Quantization"],
      score: 86,
      trend: "latest",
      citationCount: 0,
      readingMinutes: 7,
      saved: false,
      listened: false,
      processingState: "ready",
    },
    {
      id: "blog-agent-observability",
      kind: "blog",
      title: "Agent observability is becoming an infrastructure primitive",
      summary:
        "Engineering teams are moving beyond traces toward evaluations, policy checks, and replayable execution histories for production agents.",
      authors: ["SignalCast editorial"],
      sourceName: "Cloudflare Blog",
      sourceId: "source-cloudflare",
      canonicalUrl: "https://blog.cloudflare.com/",
      publishedAt: "2026-07-25T01:10:00Z",
      accessLevel: "feed_content",
      peerReviewState: "unknown",
      topics: ["AI agents", "Observability"],
      score: 84,
      trend: "latest",
      citationCount: 0,
      readingMinutes: 6,
      saved: true,
      listened: false,
      processingState: "ready",
    },
  ],
  collections: [
    {
      id: "collection-efficient-ai",
      name: "Efficient AI",
      color: "#b9ef65",
      description: "Architectures, kernels, and quantization techniques.",
      itemIds: ["paper-mamba", "paper-flashattention", "paper-bitnet"],
    },
    {
      id: "collection-agent-systems",
      name: "Agent systems",
      color: "#ff7a5c",
      description: "Planning, evaluation, observability, and tool use.",
      itemIds: ["paper-deepseek-r1", "blog-agent-observability"],
    },
  ],
  episodes: [
    {
      id: "episode-daily-0725",
      type: "daily_digest",
      title: "The Daily Signal: agents get observable",
      dek: "Reasoning models, agent infrastructure, and the quiet return of edge inference.",
      script:
        "Welcome to SignalCast. Today we are tracking three shifts: reasoning models moving from demonstrations to reinforcement learning, observability becoming core agent infrastructure, and efficient models bringing more inference back to the edge.",
      showNotes:
        "A source-grounded daily briefing. All claims are linked to their original paper or publisher.",
      transcript:
        "Welcome to SignalCast. Today we are tracking three shifts: reasoning models moving from demonstrations to reinforcement learning, observability becoming core agent infrastructure, and efficient models bringing more inference back to the edge.",
      citations: [
        {
          label: "1",
          title: "DeepSeek-R1",
          url: "https://arxiv.org/abs/2501.12948",
        },
        {
          label: "2",
          title: "BitNet b1.58",
          url: "https://arxiv.org/abs/2402.17764",
        },
      ],
      chapters: [
        { title: "The big picture", startSeconds: 0 },
        { title: "Reasoning models", startSeconds: 74 },
        { title: "Agent observability", startSeconds: 284 },
        { title: "Edge inference", startSeconds: 512 },
      ],
      audioUrl: null,
      durationSeconds: 742,
      status: "needs_approval",
      publishedAt: null,
      immutableGuid: "signalcast:episode:daily-2026-07-25",
      generation: 1,
      createdAt: "2026-07-25T06:42:00+05:30",
    },
    {
      id: "episode-flashattention",
      contentItemId: "paper-flashattention",
      type: "paper_deep_dive",
      title: "FlashAttention: the bottleneck wasn’t the math",
      dek: "Why moving fewer bytes can matter more than doing fewer operations.",
      script:
        "The central insight behind FlashAttention is architectural. Modern accelerators can perform arithmetic quickly, but moving data through the memory hierarchy is expensive. The paper reorganizes exact attention around that constraint.",
      showNotes:
        "Deep dive based on the published paper, with limitations and implementation context.",
      transcript:
        "The central insight behind FlashAttention is architectural. Modern accelerators can perform arithmetic quickly, but moving data through the memory hierarchy is expensive.",
      citations: [
        {
          label: "1",
          title: "FlashAttention paper",
          url: "https://arxiv.org/abs/2205.14135",
        },
      ],
      chapters: [
        { title: "Why attention is memory-bound", startSeconds: 0 },
        { title: "IO-aware tiling", startSeconds: 118 },
        { title: "Results and limits", startSeconds: 386 },
      ],
      audioUrl: null,
      durationSeconds: 586,
      status: "approved",
      publishedAt: null,
      immutableGuid: "signalcast:episode:flashattention",
      generation: 2,
      createdAt: "2026-07-23T18:10:00+05:30",
    },
  ],
  evidence: [
    {
      id: "evidence-r1-1",
      episodeId: "episode-daily-0725",
      contentItemId: "paper-deepseek-r1",
      claim:
        "The R1 work studies reasoning behaviors that emerge through reinforcement learning.",
      support:
        "The paper describes large-scale reinforcement learning and analyzes behaviors such as reflection and strategy adaptation.",
      sourceUrl: "https://arxiv.org/abs/2501.12948",
      confidence: 0.94,
      location: "Abstract and methodology",
    },
    {
      id: "evidence-flash-1",
      episodeId: "episode-flashattention",
      contentItemId: "paper-flashattention",
      claim:
        "FlashAttention reduces memory traffic while computing exact attention.",
      support:
        "The paper presents an IO-aware exact attention algorithm using tiling to reduce reads and writes between HBM and SRAM.",
      sourceUrl: "https://arxiv.org/abs/2205.14135",
      confidence: 0.98,
      location: "Abstract",
    },
  ],
  radar: [
    {
      id: "radar-agent-observability",
      name: "Agent observability",
      category: "Infrastructure",
      velocity: 91,
      volume: 68,
      confidence: 88,
      changeLabel: "+42% in 30d",
      itemCount: 36,
      x: 71,
      y: 24,
    },
    {
      id: "radar-reasoning-rl",
      name: "Reasoning via RL",
      category: "Models",
      velocity: 86,
      volume: 82,
      confidence: 92,
      changeLabel: "+31% in 30d",
      itemCount: 54,
      x: 54,
      y: 32,
    },
    {
      id: "radar-edge-inference",
      name: "Edge inference",
      category: "Systems",
      velocity: 74,
      volume: 58,
      confidence: 81,
      changeLabel: "+18% in 30d",
      itemCount: 28,
      x: 38,
      y: 56,
    },
    {
      id: "radar-vla",
      name: "Vision-language-action",
      category: "Robotics",
      velocity: 82,
      volume: 45,
      confidence: 79,
      changeLabel: "+27% in 30d",
      itemCount: 22,
      x: 78,
      y: 66,
    },
    {
      id: "radar-state-space",
      name: "State space models",
      category: "Models",
      velocity: 52,
      volume: 72,
      confidence: 86,
      changeLabel: "+6% in 30d",
      itemCount: 47,
      x: 26,
      y: 39,
    },
  ],
  jobs: [
    {
      id: "job-sync-0725",
      stage: "Daily source sync",
      status: "completed",
      provider: "OpenAlex + feeds",
      costUsd: 0,
      startedAt: "2026-07-25T05:30:00+05:30",
      completedAt: "2026-07-25T05:32:14+05:30",
    },
    {
      id: "job-digest-0725",
      stage: "Digest generation",
      status: "completed",
      provider: "OpenAI",
      costUsd: 0.18,
      startedAt: "2026-07-25T06:35:00+05:30",
      completedAt: "2026-07-25T06:42:00+05:30",
    },
  ],
  stats: {
    newToday: 18,
    savedItems: 5,
    listeningMinutes: 47,
    dailySpendUsd: 0.18,
    dailyBudgetUsd: 2,
    lastSync: "18 min ago",
  },
};

export function cloneDemoState(): DashboardState {
  return structuredClone(demoState);
}
