-- Run this in the Supabase SQL editor (or `supabase db push`) before deploying.
create table if not exists profiles (id text primary key, email text not null unique, display_name text not null, timezone text not null default 'Asia/Kolkata', daily_budget_usd double precision not null default 2, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists interest_profiles (id text primary key, owner_id text not null, name text not null, query text not null, keywords_json jsonb not null default '[]', exclusions_json jsonb not null default '[]', preferred_sources_json jsonb not null default '[]', freshness_days integer not null default 30, weight double precision not null default 1, enabled boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists sources (id text primary key, owner_id text not null, name text not null, type text not null, url text not null, trust_level text not null default 'trusted', rights_mode text not null default 'feed_only', enabled boolean not null default true, last_successful_fetch timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists content_items (id text primary key, owner_id text not null, kind text not null, title text not null, summary text not null default '', authors_json jsonb not null default '[]', source_name text not null, source_id text, canonical_url text not null, doi text, arxiv_id text, published_at timestamptz not null, access_level text not null default 'abstract_only', peer_review_state text not null default 'unknown', topics_json jsonb not null default '[]', score double precision not null default 0, trend text not null default 'latest', citation_count integer not null default 0, reading_minutes integer not null default 8, saved boolean not null default false, listened boolean not null default false, processing_state text not null default 'ready', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists collections (id text primary key, owner_id text not null, name text not null, color text not null default '#b9ef65', description text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists collection_items (collection_id text not null, content_item_id text not null, created_at timestamptz not null default now(), primary key (collection_id, content_item_id));
create table if not exists episodes (id text primary key, owner_id text not null, content_item_id text, type text not null, title text not null, dek text not null default '', script text not null, show_notes text not null default '', transcript text not null default '', citations_json jsonb not null default '[]', chapters_json jsonb not null default '[]', audio_url text, audio_key text, audio_bytes integer, duration_seconds integer not null default 0, status text not null default 'needs_approval', published_at timestamptz, immutable_guid text not null, generation integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists evidence (id text primary key, episode_id text not null, content_item_id text not null, claim text not null, support text not null, source_url text not null, confidence double precision not null default .8, location text not null default 'abstract', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists feedback (id text primary key, owner_id text not null, content_item_id text not null, action text not null, value integer, created_at timestamptz not null default now());
create table if not exists job_runs (id text primary key, owner_id text not null, stage text not null, status text not null, attempts integer not null default 1, provider text, cost_usd double precision not null default 0, error text, idempotency_key text not null unique, started_at timestamptz not null default now(), completed_at timestamptz);
create index if not exists interests_owner_idx on interest_profiles(owner_id); create index if not exists sources_owner_idx on sources(owner_id); create index if not exists content_owner_score_idx on content_items(owner_id, score desc); create index if not exists content_owner_published_idx on content_items(owner_id, published_at desc); create index if not exists episodes_owner_status_idx on episodes(owner_id, status); create index if not exists evidence_episode_idx on evidence(episode_id); create index if not exists feedback_owner_item_idx on feedback(owner_id, content_item_id);
-- The server uses the service-role key. Keep direct browser access disabled with RLS.
alter table profiles enable row level security; alter table interest_profiles enable row level security; alter table sources enable row level security; alter table content_items enable row level security; alter table collections enable row level security; alter table collection_items enable row level security; alter table episodes enable row level security; alter table evidence enable row level security; alter table feedback enable row level security; alter table job_runs enable row level security;
insert into storage.buckets (id, name, public) values ('podcast-media', 'podcast-media', true) on conflict (id) do update set public = true;
