-- SignalCast source bundles from SignalCast_Source_Bundles.md
-- Set preferred_owner to your profiles.id (same as login email / CRON_OWNER_EMAIL), or leave as-is to use the oldest profile.
-- 132 feeds from SignalCast_Source_Bundles.md (includes your bundle picks). IDs match in-app source-${hash(url)}.

insert into sources (id, owner_id, name, type, url, trust_level, rights_mode, enabled)
select
  v.id,
  coalesce(
    (select id from profiles where id = 'YOUR_OWNER_ID_HERE'),
    (select id from profiles order by created_at asc limit 1)
  ),
  v.name,
  v.type,
  v.url,
  'trusted',
  'feed_only',
  true
from (
  values
    ('source-1rt1fvn', 'OpenAI Blog', 'rss', 'https://openai.com/news/rss.xml'),
    ('source-d4r8bs', 'Anthropic News & Engineering', 'rss', 'https://www.anthropic.com/rss.xml'),
    ('source-fjhdr2', 'Google DeepMind Blog', 'rss', 'https://deepmind.google/blog/rss.xml'),
    ('source-pb8zdz', 'Meta AI', 'rss', 'https://ai.meta.com/blog/rss/'),
    ('source-67brms', 'Mistral AI', 'rss', 'https://mistral.ai/feed.xml'),
    ('source-ocfgu6', 'Cohere', 'rss', 'https://cohere.com/blog/rss.xml'),
    ('source-11oceqb', 'xAI', 'rss', 'https://x.ai/blog/rss.xml'),
    ('source-w4xbbx', 'Hugging Face', 'rss', 'https://huggingface.co/blog/feed.xml'),
    ('source-g4gj5y', 'Together AI', 'rss', 'https://www.together.ai/blog/rss.xml'),
    ('source-1c8g2p1', 'Fireworks AI', 'rss', 'https://fireworks.ai/blog/rss.xml'),
    ('source-1grzvm2', 'Perplexity', 'rss', 'https://www.perplexity.ai/hub/blog/rss.xml'),
    ('source-1ll28ko', 'ElevenLabs', 'rss', 'https://elevenlabs.io/blog/rss.xml'),
    ('source-1kyces3', 'AssemblyAI', 'rss', 'https://www.assemblyai.com/blog/rss/'),
    ('source-5om0bi', 'RunPod', 'rss', 'https://www.runpod.io/blog/rss.xml'),
    ('source-q84w60', 'arXiv cs.AI', 'rss', 'https://rss.arxiv.org/rss/cs.AI'),
    ('source-17eya2n', 'arXiv cs.LG', 'rss', 'https://rss.arxiv.org/rss/cs.LG'),
    ('source-11lg305', 'arXiv cs.CL', 'rss', 'https://rss.arxiv.org/rss/cs.CL'),
    ('source-ytk22f', 'arXiv cs.CV', 'rss', 'https://rss.arxiv.org/rss/cs.CV'),
    ('source-1cdhpuy', 'arXiv cs.SE', 'rss', 'https://rss.arxiv.org/rss/cs.SE'),
    ('source-1jn886z', 'arXiv cs.DC', 'rss', 'https://rss.arxiv.org/rss/cs.DC'),
    ('source-1k67hdn', 'arXiv cs.NE', 'rss', 'https://rss.arxiv.org/rss/cs.NE'),
    ('source-rki62b', 'arXiv stat.ML', 'rss', 'https://rss.arxiv.org/rss/stat.ML'),
    ('source-sffn48', 'Cloudflare', 'rss', 'https://blog.cloudflare.com/rss/'),
    ('source-1ch52ri', 'Netflix TechBlog', 'rss', 'https://netflixtechblog.com/feed'),
    ('source-e1h5cx', 'Uber Engineering', 'rss', 'https://eng.uber.com/feed/'),
    ('source-ibtrj4', 'Stripe Engineering', 'rss', 'https://stripe.com/blog/feed.rss'),
    ('source-1pbw1q0', 'Airbnb Engineering', 'rss', 'https://medium.com/airbnb-engineering/feed'),
    ('source-uvc20q', 'Discord Engineering', 'rss', 'https://discord.com/blog/rss.xml'),
    ('source-1wq2of6', 'Pinterest Engineering', 'rss', 'https://medium.com/pinterest-engineering/feed'),
    ('source-109fzsb', 'Dropbox Tech', 'rss', 'https://dropbox.tech/feed'),
    ('source-xuxb6h', 'Shopify Engineering', 'rss', 'https://shopify.engineering/feed.xml'),
    ('source-j8zcul', 'Slack Engineering', 'rss', 'https://slack.engineering/feed/'),
    ('source-1r8q3my', 'LinkedIn Engineering', 'rss', 'https://www.linkedin.com/blog/engineering/feed'),
    ('source-1qce5oj', 'GitHub Engineering', 'rss', 'https://github.blog/feed/'),
    ('source-1od2b2x', 'Google Developers', 'rss', 'https://developers.googleblog.com/feeds/posts/default'),
    ('source-4o7nvq', 'AWS Architecture Blog', 'rss', 'https://aws.amazon.com/blogs/architecture/feed/'),
    ('source-1vkc6j4', 'Microsoft Engineering', 'rss', 'https://devblogs.microsoft.com/engineering-at-microsoft/feed/'),
    ('source-1yco5a0', 'Datadog Engineering', 'rss', 'https://www.datadoghq.com/blog/feed/'),
    ('source-cleq16', 'Grafana Labs', 'rss', 'https://grafana.com/blog/index.xml'),
    ('source-80vpcg', 'Red Hat Engineering', 'rss', 'https://developers.redhat.com/blog/feed'),
    ('source-p5ycue', 'ClickHouse', 'rss', 'https://clickhouse.com/blog/rss.xml'),
    ('source-1j16a3p', 'DuckDB', 'rss', 'https://duckdb.org/feed.xml'),
    ('source-1lgy7u8', 'Turso', 'rss', 'https://turso.tech/blog/rss.xml'),
    ('source-sp6tz4', 'PlanetScale', 'rss', 'https://planetscale.com/blog/feed.xml'),
    ('source-1o09exg', 'Redis', 'rss', 'https://redis.io/feeds/all.xml'),
    ('source-13yauwv', 'Valkey', 'rss', 'https://valkey.io/blog/feed.xml'),
    ('source-ki3xfm', 'DragonflyDB', 'rss', 'https://www.dragonflydb.io/blog/rss.xml'),
    ('source-7d9zh6', 'ScyllaDB', 'rss', 'https://www.scylladb.com/feed/'),
    ('source-av37n0', 'CockroachDB', 'rss', 'https://www.cockroachlabs.com/blog/feed/'),
    ('source-30boav', 'TiDB', 'rss', 'https://www.pingcap.com/blog/feed/'),
    ('source-a2gt3x', 'Neon', 'rss', 'https://neon.tech/blog/rss.xml'),
    ('source-zy7qbs', 'Supabase', 'rss', 'https://supabase.com/blog/rss.xml'),
    ('source-13sssyg', 'MongoDB', 'rss', 'https://www.mongodb.com/blog/feed'),
    ('source-1judb12', 'Elasticsearch', 'rss', 'https://www.elastic.co/blog/feed'),
    ('source-qwdx2b', 'Qdrant', 'rss', 'https://qdrant.tech/blog/rss.xml'),
    ('source-1n9m6fx', 'Milvus', 'rss', 'https://milvus.io/blog/rss.xml'),
    ('source-tchrpr', 'Weaviate', 'rss', 'https://weaviate.io/blog/rss.xml'),
    ('source-11kz9pn', 'Vercel', 'rss', 'https://vercel.com/blog/rss.xml'),
    ('source-1riqq72', 'Fly.io', 'rss', 'https://fly.io/blog/feed/'),
    ('source-93cw5m', 'Render', 'rss', 'https://render.com/blog/rss.xml'),
    ('source-r42gry', 'Railway', 'rss', 'https://blog.railway.app/rss.xml'),
    ('source-1clo9i6', 'Netlify', 'rss', 'https://www.netlify.com/blog/rss.xml'),
    ('source-opobmh', 'DigitalOcean', 'rss', 'https://www.digitalocean.com/blog/rss.xml'),
    ('source-7nn2o6', 'AWS News Blog', 'rss', 'https://aws.amazon.com/blogs/aws/feed/'),
    ('source-10h4l44', 'Azure Blog', 'rss', 'https://azure.microsoft.com/en-us/blog/feed/'),
    ('source-rgeeer', 'Google Cloud Blog', 'rss', 'https://cloud.google.com/blog/feeds/cloud.xml'),
    ('source-vsftf8', 'Fastly', 'rss', 'https://www.fastly.com/blog/rss.xml'),
    ('source-1qrvdx7', 'Akamai', 'rss', 'https://www.akamai.com/blog/rss.xml'),
    ('source-y0bust', 'Rust Blog', 'rss', 'https://blog.rust-lang.org/feed.xml'),
    ('source-1xt0grm', 'Go Blog', 'atom', 'https://go.dev/blog/feed.atom'),
    ('source-c1rwx7', 'Python Blog', 'rss', 'https://blog.python.org/feeds/posts/default?alt=rss'),
    ('source-1ypoqbp', 'TypeScript Blog', 'rss', 'https://devblogs.microsoft.com/typescript/feed/'),
    ('source-sppgu0', 'Java Blog', 'rss', 'https://blogs.oracle.com/java/rss'),
    ('source-mrwh6d', 'Kotlin Blog', 'rss', 'https://blog.jetbrains.com/kotlin/feed/'),
    ('source-wd5v5e', 'Swift Blog', 'rss', 'https://developer.apple.com/swift/blog/rss.xml'),
    ('source-12ogi2g', 'Zig', 'rss', 'https://ziglang.org/index.xml'),
    ('source-1pvvfnb', 'Mojo', 'rss', 'https://www.modular.com/blog/rss.xml'),
    ('source-1ybpbyy', 'Next.js', 'rss', 'https://nextjs.org/feed.xml'),
    ('source-pxaj8w', 'React', 'rss', 'https://react.dev/rss.xml'),
    ('source-15i2f5v', 'Vue', 'rss', 'https://blog.vuejs.org/rss.xml'),
    ('source-1ikum75', 'Angular', 'rss', 'https://blog.angular.io/feed'),
    ('source-1i3mn09', 'Svelte', 'rss', 'https://svelte.dev/blog/rss.xml'),
    ('source-1vgabxp', 'Django', 'rss', 'https://www.djangoproject.com/rss/weblog/'),
    ('source-bm2zux', 'FastAPI', 'rss', 'https://fastapi.tiangolo.com/blog/rss/'),
    ('source-cdy8vn', 'Spring', 'atom', 'https://spring.io/blog.atom'),
    ('source-17e80i2', 'NestJS', 'rss', 'https://nestjs.com/feed.xml'),
    ('source-1s3efpa', 'Gin', 'rss', 'https://gin-gonic.com/index.xml'),
    ('source-6kr5k5', 'Fiber', 'rss', 'https://gofiber.io/blog/rss.xml'),
    ('source-1hyqk1h', 'Actix', 'rss', 'https://actix.rs/blog/rss.xml'),
    ('source-1jvktyk', 'LangChain', 'rss', 'https://blog.langchain.dev/rss/'),
    ('source-pbvdkb', 'LlamaIndex', 'rss', 'https://www.llamaindex.ai/blog/rss.xml'),
    ('source-1lsh2am', 'CrewAI', 'rss', 'https://www.crewai.com/blog/rss.xml'),
    ('source-sw75e0', 'AutoGen', 'rss', 'https://microsoft.github.io/autogen/blog/rss.xml'),
    ('source-19cf10x', 'Haystack', 'rss', 'https://haystack.deepset.ai/blog/rss.xml'),
    ('source-15v0jgt', 'DSPy', 'rss', 'https://dspy.ai/blog/rss.xml'),
    ('source-fl2w50', 'Ollama', 'rss', 'https://ollama.com/blog/rss.xml'),
    ('source-1k2tsch', 'vLLM', 'rss', 'https://vllm.ai/feed.xml'),
    ('source-1lxawub', 'SGLang', 'rss', 'https://lmsys.org/blog/rss.xml'),
    ('source-1qlp6g1', 'MLX', 'rss', 'https://ml-explore.github.io/mlx/build/html/_static/rss.xml'),
    ('source-yuni31', 'GitHub Trending', 'rss', 'https://rsshub.app/github/trending/daily/any'),
    ('source-gdjzvy', 'GitHub Releases', 'rss', 'https://github.blog/changelog/feed/'),
    ('source-pw7qv4', 'Cursor', 'rss', 'https://cursor.com/blog/rss.xml'),
    ('source-lnp7ko', 'Windsurf', 'rss', 'https://codeium.com/blog/rss.xml'),
    ('source-1jdru9s', 'VS Code', 'rss', 'https://code.visualstudio.com/feed.xml'),
    ('source-5xxrjr', 'JetBrains', 'rss', 'https://blog.jetbrains.com/feed/'),
    ('source-6ey9q9', 'Docker', 'rss', 'https://www.docker.com/blog/feed/'),
    ('source-1yizi4o', 'Podman', 'rss', 'https://podman.io/blog/rss.xml'),
    ('source-1vy3ug6', 'Kubernetes', 'rss', 'https://kubernetes.io/feed.xml'),
    ('source-1w4f334', 'Terraform', 'rss', 'https://www.hashicorp.com/blog/products/terraform/feed.xml'),
    ('source-5wgcjz', 'Pulumi', 'rss', 'https://www.pulumi.com/blog/feed/'),
    ('source-1tn03xo', 'Chatterbox TTS', 'atom', 'https://github.com/resemble-ai/chatterbox/releases.atom'),
    ('source-1f01tsb', 'Fish Speech', 'atom', 'https://github.com/fishaudio/fish-speech/releases.atom'),
    ('source-2iulcg', 'CosyVoice', 'atom', 'https://github.com/FunAudioLLM/CosyVoice/releases.atom'),
    ('source-1hscvpd', 'Qwen TTS', 'atom', 'https://github.com/QwenLM/Qwen/releases.atom'),
    ('source-b1kzrm', 'Whisper', 'atom', 'https://github.com/openai/whisper/releases.atom'),
    ('source-hzprn6', 'Faster Whisper', 'atom', 'https://github.com/SYSTRAN/faster-whisper/releases.atom'),
    ('source-oqsrjt', 'Simon Willison', 'atom', 'https://simonwillison.net/atom/everything/'),
    ('source-1fwu797', 'Lilian Weng', 'rss', 'https://lilianweng.github.io/index.xml'),
    ('source-vju3pq', 'Sebastian Raschka', 'rss', 'https://sebastianraschka.com/rss/'),
    ('source-m43k9o', 'Chip Huyen', 'rss', 'https://huyenchip.com/feed.xml'),
    ('source-143vukz', 'Andrej Karpathy', 'rss', 'https://karpathy.github.io/feed.xml'),
    ('source-3eu6gq', 'The Pragmatic Engineer', 'rss', 'https://blog.pragmaticengineer.com/rss/'),
    ('source-600352', 'ByteByteGo', 'rss', 'https://blog.bytebytego.com/feed'),
    ('source-epfnaq', 'Martin Fowler', 'atom', 'https://martinfowler.com/feeds.atom'),
    ('source-zfpw19', 'InfoQ', 'rss', 'https://feed.infoq.com/'),
    ('source-1mq9ncq', 'High Scalability', 'rss', 'https://highscalability.com/rss.xml'),
    ('source-bc0jyj', 'Hacker News', 'rss', 'https://hnrss.org/frontpage'),
    ('source-kj54iv', 'Lobsters', 'rss', 'https://lobste.rs/rss'),
    ('source-1dzxi6i', 'Reddit r/MachineLearning', 'rss', 'https://www.reddit.com/r/MachineLearning/.rss'),
    ('source-uw27mf', 'Reddit r/LocalLLaMA', 'rss', 'https://www.reddit.com/r/LocalLLaMA/.rss'),
    ('source-1bxuih0', 'Reddit r/programming', 'rss', 'https://www.reddit.com/r/programming/.rss'),
    ('source-16a27js', 'Reddit r/devops', 'rss', 'https://www.reddit.com/r/devops/.rss')
) as v(id, name, type, url)
on conflict (id) do update set
  name = excluded.name,
  type = excluded.type,
  url = excluded.url,
  enabled = excluded.enabled,
  updated_at = now();
